video_map.update({
    "스타벅스": "https://www.youtube.com/embed/Ea13UckUkoU",
    "제로콜라": "https://www.youtube.com/embed/XgtTzTLms0U",
    "마라탕": "https://www.youtube.com/embed/ymosN4zPzto",
    "불닭볶음면": "https://www.youtube.com/embed/CvPb6p-5cds",
    "노션": "https://www.youtube.com/embed/I6O9v0e1pOc",
    "쿠팡": "https://www.youtube.com/embed/VXpPGVt6iQE",
    "배달의민족": "https://www.youtube.com/embed/omdEAGGEvtE",
    "에어팟": "https://www.youtube.com/embed/x3GczcT4PtI",
    "갤럭시Z폴드": "https://www.youtube.com/embed/8l8NcGtrnbg",
    "넷플릭스": "https://www.youtube.com/embed/Wfd0ZtAk3ag",
    "마블": "https://www.youtube.com/embed/r5X-hFf6Bwo",
    "루이비통": "https://www.youtube.com/embed/fLGmiqqyQPU",
    "워케이션": "https://www.youtube.com/embed/xNBZcRMDz4E",
    "브이로그": "https://www.youtube.com/embed/2dVm3ZtD9So",
    "메타버스": "https://www.youtube.com/embed/Ia-UEYYR44s",
    "편의점": "https://www.youtube.com/embed/kGMak-UE-PI",
    "제로슈거": "https://www.youtube.com/embed/L-UF7QkzTxk",
    "스마트워치": "https://www.youtube.com/embed/H94WG-Sz7nU",
    "갤럭시워치": "https://www.youtube.com/embed/6xkz-MFipPo",
    "LG그램": "https://www.youtube.com/embed/VoL2qKCbj3E",
})
